# Iteration parameters
max_iters: 20
valid_freq: 5
checkpointing_freq: 5  # null for no checkpoints
gradient_accumulation_steps: 16
micro_batch_size: 1

# AdamW optimizer
learning_rate: 5.0e-5
beta_1: 0.9
beta_2: 0.999
weight_decay: 0.01
max_grad_norm: 2

# Cosine lr scheduler with warmup
warmup_iters: 256
lr_decay_iters: 3500
min_lr: 5.0e-8

# DataLoader
shuffle: True
drop_last: False
num_workers: 8
prefetch_factor: 8
random_seed: 1337

# Floating point
fp32_matmul_precision: high
