run_name: ???

argv_sh_file: run.sh
checkpoints_dir: checkpoints
logs_dir: logs

defaults:
  - adapter: identity_adapter/all_params
  - checkpointer: top_k_checkpointer/top_3
  - dataset: filled_python_files
  - logger: wandb_logger/context_extension
  - metrics: standard
  - model: ocoder1p5_theta_500k
  - preprocessor: lm_preprocessor/full_input_loss_12k_4k
  # +additional_preprocessor: ...
  - split: '2560_5'
  - trainer: universal_trainer/standard

  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
