pre_context_prompt: "<repo_name>{}\n<file_sep>"
post_context_prompt: "<file_sep>"
path_comment_template: "# {filename}\n{content}"

block_configs: [
  file_filtering/null_file_filter/no_args.yaml,
  file_chunking/completion_duplication_chunker/100k.yaml,
  chunk_assembling/path_comment_assembler/ocoder.yaml,
]
