pre_context_prompt: "<repo_name>{}\n"
post_context_prompt: "\n\n"
path_comment_template: "# {filename}\n{content}"

block_configs: [
  file_filtering/empty_file_filter/no_args.yaml,
  file_filtering/inclusive_file_extension_filter/python_files.yaml,
  file_preprocessing/newline_preprocessor/no_args.yaml,
  file_chunking/file_grained_chunker/no_args.yaml,
  chunk_ranking/negative_path_distance_ranker/no_args.yaml,
  chunk_ranking/iou_ranker/5.yaml,
  chunk_sorting/lexicographic_sorter/no_args.yaml,
  chunk_assembling/path_comment_assembler/standard.yaml,
  context_postprocessing/dseek_completion_leak_postprocessor/16k_5.yaml,
]
