pre_context_prompt: "<repo_name>{}\n<file_sep>"
post_context_prompt: "<file_sep>"
path_comment_template: "# {filename}\n{content}"

block_configs: [
  file_filtering/empty_file_filter/no_args.yaml,
  file_preprocessing/newline_preprocessor/no_args.yaml,
  file_chunking/file_grained_chunker/no_args.yaml,
  chunk_ranking/random_ranker/1337.yaml,
  chunk_sorting/lexicographic_sorter/no_args.yaml,
  chunk_assembling/path_comment_assembler/ocoder.yaml,
]
